// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUiiOZgebwD_XABMnO8bewAbZ85UR3rHM',
    appId: '1:220621185771:web:909e24c33c2ea0412654ae',
    messagingSenderId: '220621185771',
    projectId: 'todo-c79f1',
    authDomain: 'todo-c79f1.firebaseapp.com',
    storageBucket: 'todo-c79f1.appspot.com',
    measurementId: 'G-74BGRJKD3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBYEeJgoA40nufFzriz800iNDtabeY85w',
    appId: '1:220621185771:android:ee92530ead39c1f92654ae',
    messagingSenderId: '220621185771',
    projectId: 'todo-c79f1',
    storageBucket: 'todo-c79f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2MgvEYQgsOOU47Ylfp0mW6ZjLbTvdnTU',
    appId: '1:220621185771:ios:1c71d42a5dc9d3452654ae',
    messagingSenderId: '220621185771',
    projectId: 'todo-c79f1',
    storageBucket: 'todo-c79f1.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2MgvEYQgsOOU47Ylfp0mW6ZjLbTvdnTU',
    appId: '1:220621185771:ios:1c71d42a5dc9d3452654ae',
    messagingSenderId: '220621185771',
    projectId: 'todo-c79f1',
    storageBucket: 'todo-c79f1.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUiiOZgebwD_XABMnO8bewAbZ85UR3rHM',
    appId: '1:220621185771:web:24aaee77b50ac2292654ae',
    messagingSenderId: '220621185771',
    projectId: 'todo-c79f1',
    authDomain: 'todo-c79f1.firebaseapp.com',
    storageBucket: 'todo-c79f1.appspot.com',
    measurementId: 'G-7TV08TGHBF',
  );
}
